### ISSUE TITLE
feat: seed CRUD operations

### ISSUE THREAD

**Issue by adnanbubalo** [UdL-EPS-SoftArch/seedbank-gei#8]
- [x] List
- [x] Details
- [x] Create
- [x] Delete
- [x] Update

**Comment by rogargon** [comment]
Closing this issue as seed CRUD operations have already been implemented. For the pending form validation use the corresponding issue and open a new branch for it: https://github.com/UdL-EPS-SoftArch/seedbank-gei/issues/25
